Fixed utf-8 decoding error
Fixed this error:

ERROR: 'utf-8' codec can't decode byte 0x80 in position 2818: invalid start byte

It happens because indeed there is a 0x80 byte in the middle of `Extra descriptor` at the EDID information.